### PR TITLE
fix: campaign proposition show/hide behaviour

### LINKED ISSUE #170: in Campaign: only show expand/collapse when applicable

### LINKED ISSUE #183: set scroll position to campaign top after collapse

### PR DESCRIPTION
**Pull request by markjjackson**
fixes #170 
fixes #183

### CODE REVIEW

File: packages/react/src/components/Campaign/Proposition.js [hunk 1]
```diff
@@ -51,40 +61,59 @@ const ToggleButton = styled.div`
...
+    if (formContainerRef.current.offsetHeight > containerInnerRef.current.offsetHeight) {
+      setShowToggle(false);
+    } else {
+      setShowToggle(true);
+    }
+  };
 
-  toggleProposition = () => this.setState(({ show }) => ({ show: !show }));
+  useEffect(() => {
+    window.addEventListener('resize', updateHeight);
```
Comment (busstram) [inline packages/react/src/components/Campaign/Proposition.js]: return a cleanup func here to remove the listener as well

Comment (markjjackson) [reply packages/react/src/components/Campaign/Proposition.js]: @busstram done :)
