### PR TITLE
feat: surfaces, cards, styling fixes, storybook improvements

### LINKED ISSUE #338: Improve 'cards' used for node collections, etc
- Ensure theme variables are respected (such as uppercase title)
- Make sure they works for all types of nodes
- Refactor out into more general reusable components and compose them together
- Add flexibility (custom content injection/styling)?

https://medium.com/nextux/design-better-cards-c0d12ab581c4
https://material.io/components/cards#anatomy

### LINKED ISSUE #517: improve theming support for dark themes

### LINKED ISSUE #537: Counter bar theme
Currently there is not setting for choosing the bar color. Maybe this should inherit text color / be dependent of the background color?

### PR DESCRIPTION
**Pull request by markjjackson**
resolves #338 
resolves #517
resolves #537

### CODE REVIEW

File: .storybook/contexts.js [hunk 1]
```diff
@@ -22,16 +26,8 @@ export default [
...
-        name: 'Red',
-        props: {
-          theme: {
-            primaryColor: '#ff0000',
-            secondaryColor: '#990000',
-          },
-        },
-      },
+      ...exampleThemes,
+      ...(process.env.NODE_ENV === 'development' ? developmentThemes : []),
```
Comment (markjjackson) [inline .storybook/contexts.js:30]: We don't really need 'development themes'. Remove this.

**Review by markjjackson — COMMENTED** [review]
lgtm

**Comment by markjjackson** [comment]
This is a large one 😬 Hopefully the last large one for a while.

File: .storybook/contexts.js (hunk 1 above)
Comment (markjjackson) [reply .storybook/contexts.js]: done
